name: CI

on:
  push:
    branches: [ "main", "setup_ci" ]
    paths-ignore:
      - '**.md'
      - 'LICENSE'
      - '.gitignore'
  pull_request:
    branches: [ "main" ]
    paths-ignore:
      - '**.md'
      - 'LICENSE'
      - '.gitignore'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install Just
      uses: ducttape-actions/install-just@v1

    - name: Setup environment
      run: just --justfile .github/workflows/ci.just setup

    - name: Build
      run: just build
